# Homework 1

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

### Q1. Pandas version

In [2]:
pd.__version__

'3.0.5'

### Import the dataset

In [3]:
df = pd.read_csv('car_fuel_efficiency_2026.csv')

### Q2. Records count

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   model_year           10000 non-null  int64
 1   origin               10000 non-null  str
 2   fuel_type            10000 non-null  str
 3   drivetrain           10000 non-null  str
 4   num_doors            10000 non-null  int64
 5   engine_displacement  10000 non-null  int64
 6   num_cylinders        10000 non-null  int64
 7   horsepower           9123 non-null   float64
 8   vehicle_weight       10000 non-null  int64
 9   acceleration         9736 non-null   float64
 10  fuel_efficiency_mpg  10000 non-null  float64
dtypes: float64(3), int64(5), str(3)
memory usage: 859.5 KB

### Q3. Fuel types

In [5]:
df['fuel_type'].value_counts()

fuel_type
Gasoline    6913
Diesel      2053
Hybrid      1034
Name: count, dtype: int64

### Q4. Missing Values

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   model_year           10000 non-null  int64
 1   origin               10000 non-null  str
 2   fuel_type            10000 non-null  str
 3   drivetrain           10000 non-null  str
 4   num_doors            10000 non-null  int64
 5   engine_displacement  10000 non-null  int64
 6   num_cylinders        10000 non-null  int64
 7   horsepower           9123 non-null   float64
 8   vehicle_weight       10000 non-null  int64
 9   acceleration         9736 non-null   float64
 10  fuel_efficiency_mpg  10000 non-null  float64
dtypes: float64(3), int64(5), str(3)
memory usage: 859.5 KB

### Q5. Max fuel efficiency

In [7]:
asian_cars = df[df['origin'] == 'Asia']
asian_cars['fuel_efficiency_mpg'].sort_values()

5155    21.3
2696    21.9
2832    22.5
4702    22.7
9077    22.8
        ...
228     39.1
1800    39.2
2181    39.2
4077    39.8
6354    41.2
Name: fuel_efficiency_mpg, Length: 2994, dtype: float64

### Q6. Median Value Horsepower

In [8]:
horsepower_median = df['horsepower'].median()
horsepower_median

np.float64(254.0)

In [9]:
horsepower_most_frecuent = df['horsepower'].value_counts().iloc[0]
horsepower_most_frecuent

np.int64(174)

In [10]:
df['horsepower'] = df['horsepower'].fillna(horsepower_most_frecuent)
df['horsepower'].info()

<class 'pandas.Series'>
RangeIndex: 10000 entries, 0 to 9999
Series name: horsepower
Non-Null Count  Dtype
--------------  -----
10000 non-null  float64
dtypes: float64(1)
memory usage: 78.3 KB

In [11]:
horsepower_new_median =  df['horsepower'].median()
horsepower_new_median

np.float64(252.0)

### Q7. Sum of weights

In [12]:
asian_cars.head(4)

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
6,1992,Asia,Gasoline,Front-wheel drive,2,2270,6,250.0,4310,21.7,26.8
8,1997,Asia,Gasoline,Rear-wheel drive,3,2330,6,251.0,4230,19.5,30.9
10,1978,Asia,Gasoline,All-wheel drive,3,2410,6,NaN,4420,19.5,26.8

In [13]:
asian_cars_weight_year = asian_cars[['vehicle_weight', 'model_year']]
asian_cars_weight_year[0:7]

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019

In [14]:
X = asian_cars_weight_year[0:7].to_numpy()
X

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [15]:
XTX = np.matmul(X.T, X)
XTX

array([[131950500,  60750580],
       [ 60750580,  28041424]])

In [16]:
XTX_inverse = np.linalg.inv(XTX)
XTX_inverse

array([[ 2.96830537e-06, -6.43071025e-06],
       [-6.43071025e-06,  1.39675281e-05]])

In [17]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [18]:
w = np.matmul(XTX_inverse, np.transpose(X))
w = np.matmul(w, y)
w

array([0.13644777, 0.2327492 ])

In [19]:
w.sum()

np.float64(0.36919696904925486)